# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY src ./src
RUN npm run build

# Final image
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and dependencies
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./
RUN npm ci --production --ignore-scripts

# Default command (can be overridden by MCP start command)
ENTRYPOINT ["node", "dist/bot.js"]
